### ISSUE TITLE
Problems at first glance

### ISSUE THREAD

**Issue by jc5504** [mattmarek/sm4sh-mod-collection#1]
On little mac's victory animation, his belt clips with his hood in the new textures. The belt should instead rest on top of the hood, like it does with the default pink hood.
Sometimes, Mushroom Kingdom U is silent. I'm not sure why, since all of the tracks work in "my music". I was not able to observe which song was supposed to be playing when that happened, I'll get back on that.
With the reorganization of the character roster, all the dlc characters were unlocked. Not sure if this was intentional, but if it was, then I suggest you also unlock the stage dlc.

But problems aside, great mod pack. Nice selection of music and textures.

**Comment by mattmarek** [comment]
Closing this issue to re-open as individual issues
